Vagrant.configure("2") do |config|

  config.vm.define "jenkins" do |j|
    j.vm.box = "ubuntu/xenial64"
    j.vm.hostname = "jenkins"
    j.vm.network :private_network, ip: "192.168.3.10"
    j.vm.provision "shell", path: "config.sh"
    j.vm.provider "virtualbox" do |vb|
      vb.name = "jenkins"
      vb.memory = 512
      vb.cpus = 1
    end
  end

end
