Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "master"
  config.vm.network :private_network, ip: "192.168.3.5"
  config.vm.synced_folder "shared", "/home/vagrant/projects"
  config.vm.provision "shell", path: "config-ansible.sh", privileged: false
  config.vm.provider "virtualbox" do |vb|
    vb.name = "master"
    vb.memory = 512
    vb.cpus = 1
  end

end
